### ISSUE TITLE
访问 https://zhubai.wiki/  加载不出数据

### ISSUE THREAD

**Issue by PipecraftNet** [senlypan/zhubai-wiki-docs#1]
如题，访问 https://zhubai.wiki/  都加载不出数据，只有访问 https://www.zhubai.wiki/ 才出来。
每次都是直接输入域名访问竹白百科，刷新好几次，都不出来，还以为网络有问题。后来才发现是域名不对。

建议访问 https://zhubai.wiki/  时，自动跳转到 https://www.zhubai.wiki/ 。

**Comment by senlypan** [comment]
感谢建议，后端服务跨域配置遗漏，已处理，多谢。
